name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Vulkan SDK (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
        sudo apt-get update
        sudo apt-get install -y vulkan-sdk

    - name: Install Vulkan SDK (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install --cask vulkan-sdk

    - name: Install Vulkan SDK (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install vulkan-sdk -y

    - name: Install CMake (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main'
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install CMake (macOS)
      if: runner.os == 'macOS'
      run: brew install cmake

    - name: Install CMake (Windows)
      if: runner.os == 'Windows'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release
